worker_processes 1;

pid /tmp/freenginx.pid;

events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;

  sendfile on;
  client_body_temp_path /tmp/client_temp;

  proxy_temp_path /tmp/proxy_temp;
  keepalive_timeout 65;

  fastcgi_temp_path /tmp/fastcgi_temp;

  # https://freenginx.org/en/docs/http/ngx_http_headers_module.html
  map $sent_http_content_type $expires {
    default off;
    text/html epoch;
    text/css 1d;
    application/javascript 1d;
    application/json 1d;
    font/woff2 max;
    ~image/ 7d;
  }

  server {
    listen 8081;
    server_name admin.peony.com;

    # https://freenginx.org/en/docs/http/ngx_http_gzip_static_module.html
    gzip_static on;

    location = / {
      alias /srv/build/;
      expires $expires;
      add_header Cache-Control "public, no-transform";
    }
  }
}
